# Generated by Django 5.2.6 on 2025-09-09 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PuntoVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("nit", models.CharField(blank=True, max_length=30)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nombre"],
                "unique_together": {("nombre", "nit")},
            },
        ),
        migrations.CreateModel(
            name="Factura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_factura", models.DateField()),
                ("numero_factura", models.CharField(max_length=60)),
                ("valor_factura", models.DecimalField(decimal_places=2, max_digits=14)),
                ("fecha_pago_estimada", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcial"),
                            ("PAGADA", "Pagada"),
                        ],
                        default="PENDIENTE",
                        max_length=10,
                    ),
                ),
                (
                    "total_pagado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="facturas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cartera.proveedor",
                    ),
                ),
                (
                    "punto_venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cartera.puntoventa",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_factura", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pago", models.DateField()),
                ("valor_pagado", models.DecimalField(decimal_places=2, max_digits=14)),
                ("comprobante", models.FileField(upload_to="comprobantes/%Y/%m/%d/")),
                ("notas", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="cartera.factura",
                    ),
                ),
                (
                    "pagado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_pago", "-id"],
                "indexes": [
                    models.Index(
                        fields=["fecha_pago"], name="cartera_pag_fecha_p_d5d1d3_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(fields=["estado"], name="cartera_fac_estado_6270d5_idx"),
        ),
        migrations.AddIndex(
            model_name="factura",
            index=models.Index(
                fields=["fecha_factura"], name="cartera_fac_fecha_f_7a8dab_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="factura",
            unique_together={("punto_venta", "numero_factura")},
        ),
    ]
