# Generated by Django 5.2.6 on 2025-09-09 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartera", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="factura",
            options={},
        ),
        migrations.AlterModelOptions(
            name="pago",
            options={},
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="cartera_fac_estado_6270d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="factura",
            name="cartera_fac_fecha_f_7a8dab_idx",
        ),
        migrations.RemoveIndex(
            model_name="pago",
            name="cartera_pag_fecha_p_d5d1d3_idx",
        ),
        migrations.RenameField(
            model_name="proveedor",
            old_name="correo",
            new_name="email",
        ),
        migrations.AlterUniqueTogether(
            name="factura",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="proveedor",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="puntoventa",
            name="activo",
        ),
        migrations.AddField(
            model_name="proveedor",
            name="creado_en",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="proveedor",
            name="telefono",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="puntoventa",
            name="ciudad",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="puntoventa",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="punto_venta",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="estado",
            field=models.CharField(
                choices=[("pendiente", "Pendiente"), ("pagada", "Pagada")],
                default="pendiente",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="factura",
            name="numero_factura",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="pago",
            name="comprobante",
            field=models.FileField(blank=True, upload_to="comprobantes/"),
        ),
        migrations.AlterField(
            model_name="pago",
            name="pagado_por",
            field=models.CharField(blank=True, default="Admin", max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="proveedor",
            name="nit",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="puntoventa",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name="factura",
            name="fecha_pago_estimada",
        ),
        migrations.RemoveField(
            model_name="proveedor",
            name="activo",
        ),
    ]
