# Generated by Django 5.2.6 on 2025-09-10 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cartera", "0003_puntoventausuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="factura",
            name="confirmado_fecha",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="factura",
            name="confirmado_pago",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="factura",
            name="confirmado_por_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
