# Generated by Django 5.2.6 on 2025-09-16 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0004_factura_confirmado_fecha_factura_confirmado_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/'),
        ),
        migrations.CreateModel(
            name='PagoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('pagado_por', models.CharField(max_length=150)),
                ('comprobante', models.FileField(upload_to='comprobantes/')),
                ('notas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='cartera.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='pago',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='cartera.pagolote'),
        ),
    ]
