# Generated by Django 5.2.6 on 2026-04-15 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0006_correoenviolog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'ordering': ['-fecha_factura', '-id']},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_pago', '-id']},
        ),
        migrations.AlterModelOptions(
            name='pagolote',
            options={'ordering': ['-fecha_pago', '-id']},
        ),
        migrations.RenameIndex(
            model_name='correoenviolog',
            new_name='cartera_cor_tipo_dcd82f_idx',
            old_name='cartera_cor_tipo_0d329d_idx',
        ),
        migrations.RenameIndex(
            model_name='correoenviolog',
            new_name='cartera_cor_factura_5936ff_idx',
            old_name='cartera_cor_factur_0df4e8_idx',
        ),
        migrations.RenameIndex(
            model_name='correoenviolog',
            new_name='cartera_cor_lote_id_937497_idx',
            old_name='cartera_cor_lote_4dff6b_idx',
        ),
    ]
