# Generated by Django 5.2.6 on 2026-06-10 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0007_alter_factura_options_alter_pago_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('factura_creada', 'Creacion de factura'), ('factura_editada', 'Edicion de factura'), ('pago_creado', 'Creacion de pago'), ('pago_eliminado', 'Eliminacion de pago'), ('correo_enviado', 'Envio de correo'), ('confirmacion_factura_publica', 'Confirmacion publica de factura'), ('confirmacion_lote_publica', 'Confirmacion publica de lote')], db_index=True, max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='cartera.factura')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='cartera.pagolote')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria', to='cartera.pago')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_auditoria_cartera', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de auditoria',
                'verbose_name_plural': 'Eventos de auditoria',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['tipo', 'creado_en'], name='cartera_eve_tipo_82b60d_idx'), models.Index(fields=['factura', 'creado_en'], name='cartera_eve_factura_5e1c2e_idx'), models.Index(fields=['pago', 'creado_en'], name='cartera_eve_pago_id_431b92_idx'), models.Index(fields=['lote', 'creado_en'], name='cartera_eve_lote_id_57ac43_idx')],
            },
        ),
    ]
