# Generated by Django 5.2.6 on 2026-06-10 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartera', '0008_eventoauditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoauditoria',
            name='tipo',
            field=models.CharField(choices=[('factura_creada', 'Creacion de factura'), ('factura_editada', 'Edicion de factura'), ('pago_creado', 'Creacion de pago'), ('pago_eliminado', 'Eliminacion de pago'), ('correo_enviado', 'Envio de correo'), ('confirmacion_factura_publica', 'Confirmacion publica de factura'), ('confirmacion_lote_publica', 'Confirmacion publica de lote'), ('confirmacion_pago_portal', 'Confirmacion de pago desde portal proveedor'), ('confirmacion_lote_portal', 'Confirmacion de lote desde portal proveedor'), ('comprobante_visualizado', 'Visualizacion de comprobante'), ('novedad_proveedor', 'Novedad reportada por proveedor'), ('notificacion_generada', 'Notificacion generada'), ('notificacion_leida', 'Notificacion marcada como leida')], db_index=True, max_length=60),
        ),
        migrations.CreateModel(
            name='NotificacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago_registrado', 'Pago registrado'), ('lote_registrado', 'Lote registrado'), ('correo_enviado', 'Correo enviado'), ('confirmacion_pago', 'Confirmacion de pago'), ('confirmacion_lote', 'Confirmacion de lote'), ('novedad', 'Novedad'), ('sistema', 'Sistema')], db_index=True, max_length=40)),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField(blank=True)),
                ('leida', models.BooleanField(default=False)),
                ('url_destino', models.CharField(blank=True, max_length=255)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_proveedor', to='cartera.factura')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_proveedor', to='cartera.pagolote')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_proveedor', to='cartera.pago')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='cartera.proveedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_proveedor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion de proveedor',
                'verbose_name_plural': 'Notificaciones de proveedores',
                'ordering': ['-creada_en', '-id'],
                'indexes': [models.Index(fields=['usuario', 'leida', 'creada_en'], name='cartera_not_usuario_7f808b_idx'), models.Index(fields=['proveedor', 'tipo', 'creada_en'], name='cartera_not_proveed_e83ed8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProveedorUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('puede_confirmar_pagos', models.BooleanField(default=True)),
                ('recibe_notificaciones', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_portal', to='cartera.proveedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores_portal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de proveedor',
                'verbose_name_plural': 'Usuarios de proveedores',
                'ordering': ['proveedor__nombre', 'user__username'],
                'indexes': [models.Index(fields=['user', 'activo'], name='cartera_pro_user_id_3a6136_idx'), models.Index(fields=['proveedor', 'activo'], name='cartera_pro_proveed_dd0d1a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'proveedor'), name='unique_usuario_proveedor_portal')],
            },
        ),
    ]
